source "${HOME}/.zgen/zgen.zsh"

# if the init script doesn't exist
#if ! zgen saved; then

  # specify plugins here
  zgen oh-my-zsh
  zgen oh-my-zsh plugins/git
  zgen oh-my-zsh plugins/vi-mode
  zgen oh-my-zsh plugins/docker
  zgen oh-my-zsh plugins/history
  zgen oh-my-zsh themes/agnoster
  zgen load zsh-users/zsh-syntax-highlighting
  zgen load zsh-users/zsh-autosuggestions
  zgen load zsh-users/zsh-syntax-highlighting
  zgen load superbrothers/zsh-kubectl-prompt

  # generate the init script from plugins above
  zgen save
#fi

# Load plugins and theme
source ~/.zsh/config/env.zsh

#zstyle ':prezto:module:tmux:auto-start' local 'yes'
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

# Setup fzf install directory
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

RPROMPT='%{$fg[blue]%}($ZSH_KUBECTL_PROMPT)%{$reset_color%}'
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle :compinstall filename '/home/diego/.zshrc'

autoload -Uz compinit; colors; colors
compinit

#asdf version manager source
. $HOME/.asdf/asdf.sh
